language: python
dist: bionic
python:
  - "3.6"
addons:
  apt:
    packages:
    - gir1.2-gtk-3.0
    - libgirepository1.0-dev
    - libapt-pkg-dev
install:
  - pip install -r requirements.txt
script: 
  - ./runtests pep8 small
